# Generated by Django 4.2.6 on 2023-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(default='Unknown', max_length=50)),
                ('password', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='password',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='teacher',
        ),
    ]
